### ISSUE TITLE
Can you please check if the count query is working fine. for me they are not returning the result as the return type is not proper

### ISSUE THREAD

**Issue by neeraj04neeru** [Azure-Samples/azure-spring-data-cosmos-java-sql-api-samples#11]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by neeraj04neeru** [comment]
I am using the following query SELECT  VALUE COUNT(1) FROM FileS c WHERE ( c.uploadDate BETWEEN @fromDate AND @toDate )

**Comment by seesharprun** [comment]
Resolves #12

**Comment by seesharprun** [comment]
It looks like the query sample at the end breaks the sample app. I reworked the query sample to instead query:

```sql
SELECT VALUE COUNT(1) FROM users
```

**Comment by seesharprun** [comment]
I validated this now works by opening the repository in a codespace, getting a new account and credentials from <https://cosmos.azure.com/try>, and then running `mvn spring-boot:run`
