### ISSUE TITLE
This code cannot work with serverless plan!

### ISSUE THREAD

**Issue by hatasaki** [Azure-Samples/azure-spring-data-cosmos-java-sql-api-samples#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
This code cannot run with serverless plan CosmosDB, because it doesn't support Provisioned Troughput

### Any log messages given by the failure
>
"Setting offer throughput or autopilot on container is not supported for serverless accounts.\r\nActivityId: ****, Microsoft.Azure.Documents.Common/2.14.0, StatusCode: BadRequest"

### Mention any other details that might be useful
It works fine if you modify User.java at line 8, 
Original:
@Container(containerName = "myContainer", ru = "400")
Modified:
@Container(containerName = "myContainer")

This repository linked from QuickStart MS document and most user may use serverless plan for evaluation. So please correct it ASAP! (Write some guidance in README or update the code.)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by seesharprun** [comment]
I believe you are right that we should update this repository to not set a throughput amount when creating the container. This will fail for serverless accounts. I need to do some quick testing to make sure the default throughput (when not specified) for provisioned accounts isn't a very large number.

**Comment by seesharprun** [comment]
I have finished testing and have found that if you omit the `RU` parameter, it will work with both serverless and provisioned accounts. I also determined that the default RU for provisioned accounts is **400** which is acceptable. I will issue a PR to fix this issue. Thanks @hatasaki for reporting it!

I validated the provisioned acocunt using <https://cosmos.azure.com/try/>
