### ISSUE TITLE
Found typo: Should be "SELECT" instead of "ELECT" ;)

### ISSUE THREAD

**Issue by emzet92** [Azure-Samples/azure-spring-data-cosmos-java-sql-api-samples#2]
https://github.com/Azure-Samples/azure-spring-data-cosmos-java-sql-api-samples/blob/456b1fb767b77aae7bcf5cf0965c27fcec66a0f2/src/main/java/com/azure/cosmos/springexamples/quickstart/sync/UserRepository.java#L44-L46

**Comment by TheovanKraay** [comment]
closed with pr https://github.com/Azure-Samples/azure-spring-data-cosmos-java-sql-api-samples/pull/7
